dist: trusty
language: ruby


sudo: required
services:
  - docker


script: |
  .travis.d/build.sh &&
  cd .travis.d &&
  bundle install --gemfile=Gemfile --path vendor/bundle

env:
  global:
    - HACKGPROJECT_REV="a5f78884380e1cb082369d74577b3998f0d44c12"

    - DOCKER_ID_USER="hackgt"
