# This file defines some parameters that will affect the live site as a whole.
title: HackGT Live
description: >- # >- means ignore newlines until "baseurl:"
  Write an awesome description for your live site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results).
baseurl: "" # the base subpath of this site; that is, if your pages have a constant prefix, like /live, add that here
url: # Your site's domain, e.g. everything up and including to the .com
# Social media links are defined in _data/social_media.yaml
form_id: 1FAIpQLSdP3yiCMb4sSztn32tdwtDiZXud0vJNbUql-LD8au6noNTRqA # This is the form ID contained in the view URL of the site feedback form in the footer
feedback: Give our site feedback!
oneSignalAppId: 412f86d5-9c3d-4f7c-aa7b-d2a50025b8c7
url: https://docs.google.com/forms/d/e/1FAIpQLSdP3yiCMb4sSztn32tdwtDiZXud0vJNbUql-LD8au6noNTRqA/viewform?entry.1073143569={{ page.url| cgi_escape | escape }}&entry.267778992={{ page.title| cgi_escape | escape }}&entry.2080441427&entry.1331555321&entry.278526493


# Hi!  There's a lot of interesting stuff under me, but if you touch it, you might break something!  Please don't edit anything below this line unless you know what you're doing!
collections:
  event_pages:
    output: true
    permalink: /:name/
  blocks:
    output: false

defaults:
    -
        scope:
            path: "_event_pages"
        values:
            priority: 1
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .bundle
  - vendor
  - Dockerfile
  - .dockerignore
  - .gitignore
  - docker_resources
  - deployment.yaml
  - precheck.rb
  - LICENSE
