# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: BuildGT
email: hello@hack.gt
description: >- # this means to ignore newlines until "baseurl:"
  Twelve-hour hardware hackathon brought to you by HackGT and the Invention Studio
baseurl: "" # the subpath of your site, e.g. /blog
url: https://live.build.hack.gt
twitter_username: TheHackGT
github_username:  HackGT
facebook_username: HackGT
form_id: 1FAIpQLSdP3yiCMb4sSztn32tdwtDiZXud0vJNbUql-LD8au6noNTRqA
feedback: Give our site feedback!
oneSignalAppId: 412f86d5-9c3d-4f7c-aa7b-d2a50025b8c7

collections:
  event_pages:
    output: true
    permalink: /:name/
  blocks:
    output: false

defaults:
    -
        scope:
            path: "_event_pages"
        values:
            priority: 1
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .bundle
  - vendor
  - Dockerfile
  - .dockerignore
  - .gitignore
  - docker_resources
  - deployment.yaml
  - precheck.rb
  - LICENSE

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
