# This file defines some parameters that will affect the live site as a whole.
title: Catalyst
description: >- # >- means ignore newlines until "baseurl:"
  HackGT presents Catalyst, a FREE day of STEAM directed towards high school students in the Metro Atlanta Area. We are eager to welcome 400+ students on Saturday April 13th, from 9 AM to 9 PM to Georgia Tech's Campus, making it one of the largest high school learn-a-thons hosted in the country.
baseurl: "" # the base subpath of this site; that is, if your pages have a constant prefix, like /live, add that here
url: https://live-site.dev.hack.gt # Your site's domain, e.g. everything up and including to the .com
# Social media links are defined in _data/social_media.yaml
form_id: 1FAIpQLSdP3yiCMb4sSztn32tdwtDiZXud0vJNbUql-LD8au6noNTRqA # This is the form ID contained in the view URL of the site feedback form in the footer
feedback: Give our site feedback!
enableOneSignal: true
oneSignalAppId: 0a865164-8f5e-42b7-9c83-a63b8d99c27a


# Hi!  There's a lot of interesting stuff under me, but if you touch it, you might break something!  Please don't edit anything below this line unless you know what you're doing!
collections:
  event_pages:
    output: true
    permalink: /:path/
  blocks:
    output: false

defaults:
    -
        scope:
            path: "_event_pages"
        values:
            priority: 1
# Build settings
markdown: kramdown
theme: minima

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .bundle
  - vendor
  - Dockerfile
  - .dockerignore
  - .gitignore
  - docker_resources
  - deployment.yaml
  - precheck.rb
  - LICENSE
